### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by georgeburdell**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-86205` branch.

**Before merging**, you need to:

- Checkout the `shift-86205` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by georgeburdell** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 10 versions](https://github.com/laravel-shift/laravel-10.x/) and merge any changes:

- [ ] app/Http/Middleware/Authenticate.php
- [ ] lang/en/validation.php

**Comment by georgeburdell** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/RoboJackets/apiary/pull/3479/commits/9ad1ee545b99babde46aadd0b52f2f83c456c7d5?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 9ad1ee54` and make the [config file changes](https://github.com/laravel-shift/laravel-9.x/pull/4/commits/5401110f1f41793ecdce268495768abfa4a53dfe) manually.

**Comment by georgeburdell** [comment]
:information_source: Shift [updated your dependencies](https://github.com/RoboJackets/apiary/pull/3479/commits/c1da282a8acfd6e76c1f465dd01b6218d5debc4c?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [chelout/laravel-relationship-events](https://packagist.org/packages/chelout/laravel-relationship-events)
- [ ] [htmlmin/htmlmin](https://packagist.org/packages/htmlmin/htmlmin)
- [ ] [realrashid/sweet-alert](https://packagist.org/packages/realrashid/sweet-alert)

**Comment by georgeburdell** [comment]
:information_source: Shift detected your application has a test suite. To make verifying the upgrade to Laravel 10 easier, Shift did not upgrade your test suite to PHPUnit 10.

Once you have completed your upgrade, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free to upgrade your test suite to PHPUnit 10 separately.

**Comment by georgeburdell** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/RoboJackets/apiary/pull/3479/commits/30efbeaac8c3bf1a4f1925e29653388930d60c08?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by georgeburdell** [comment]
:warning: Laravel 10 has added a return type of `array` to the Event `broadcastOn` and Notification `via` methods. However, you may still return a single channel from these methods.

Shift added the `array` return type to these methods in the following classes. You should review them to ensure you are returning an `array`, or remove the return type.

- [ ] app/Notifications/Dues/PaymentReminder.php
- [ ] app/Notifications/Dues/SummaryNotification.php
- [ ] app/Notifications/Dues/TransactionReminder.php
- [ ] app/Notifications/ExpiringPersonalAccessTokenNotification.php
- [ ] app/Notifications/GlobalAttendanceNotification.php
- [ ] app/Notifications/MembershipAgreementDocuSignEnvelopeReceived.php
- [ ] app/Notifications/MembershipAgreementSigned.php
- [ ] app/Notifications/PaymentReceipt.php
- [ ] app/Notifications/TeamAttendanceNotification.php
- [ ] app/Notifications/Travel/AllTravelAssignmentsComplete.php
- [ ] app/Notifications/Travel/DocuSignEnvelopeReceived.php
- [ ] app/Notifications/Travel/TravelAssignmentCreated.php
- [ ] app/Notifications/Travel/TravelAssignmentReminder.php

**Comment by georgeburdell** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/RoboJackets/apiary/pull/3479/commits/813a2c774390f5c2e4cedd60c2ec5d8d439ed6d9?w=1) to any method which is used by Laravel, as well as any method which had types defined in its PHP DocBlock.

**Comment by georgeburdell** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/RoboJackets/apiary/pull/3479/commits/1bfa6e7d21c599074871bc92d8497fd3260ee910?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by georgeburdell** [comment]
:information_source: Shift understands you may wish to preserve your full DocBlock even with PHP type hints in code. All of Shift's automation is done in nice, atomic commits. So you may easily undo this change by running `git revert 1bfa6e7d`.

**Comment by georgeburdell** [comment]
:warning: In Laravel 10 you may no longer directly cast a `DB:raw()` expression to a string. Instead, you must retrieve the value from the expression using the `getValue()` method.

Shift detected calls to `DB::raw()`. You should review these instances to see if you are casting the result to a string.

- [ ] app/Models/User.php
- [ ] app/Nova/Metrics/AttendancePerWeek.php

**Comment by georgeburdell** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. You should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by georgeburdell** [comment]
:information_source: Laravel began using Vite to build frontend assets in Laravel 9.19. While you may continue to use Laravel Mix, it is no longer the default. If you wish to modernize your application to use Vite, you may run the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite) for free.

**Comment by georgeburdell** [comment]
:warning: Shift detected your application contains stub files. With all of the type hints added in Laravel 10, you should review these files and add any type hints you want to have when generating classes with `artisan make`.

**Comment by georgeburdell** [comment]
:warning: Laravel 10 requires Composer 2.2 or higher. You should verify the Composer version in your environments by running `composer --version` to ensure it meets this new requirement. If necessary, run `composer self-update` to update Composer.

**Comment by georgeburdell** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by georgeburdell** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Review by kberzinch — APPROVED** [review]

**Pull request merged**
