### PR TITLE
Preferred name defaults to legal name on user edit form

### LINKED ISSUE #226: Preferred Name copy
Change input label to "Preferred First Name". Pre-fill with legal first name.

These changes should clarify the purpose of the field.

### PR DESCRIPTION
**Pull request by kberzinch**
This is arguably kind of dumb and should start a discussion about how we store and handle names.

Closes #226

### CODE REVIEW

**Comment by ryanstrat** [comment]
I don't agree with this change.

I like the new storage logic, but I think that we should continue returning null for the preferred name field if one is not set.

**Comment by kberzinch** [comment]
Why?

**Comment by ryanstrat** [comment]
Because the field is null. I don't think we should misrepresent it. Plus, iirc we have a separate field that contains first or preferred,

**Comment by kberzinch** [comment]
That field is `preferred_name`.

**Comment by ryanstrat** [comment]
But basically, the current implementation makes it impossible for the frontend to determine the true state of the database, which is the root of my displeasure.

**Comment by kberzinch** [comment]
I think this is what you want @ryanstrat

**Comment by kberzinch** [comment]
I don't think so. The admin edit page is the same vue component afaik.

**Pull request merged**
