### PR TITLE
Dependency Updater

### PR DESCRIPTION
**Pull request by georgeburdell**
This pull request includes minor version updates for your package dependencies as well as major version updates for packages with known compatibility. Feel free to commit any additional changes to the `shift-du-20190903` branch.

**Before merging**, you should:

- Checkout the `shift-du-20190903` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

### CODE REVIEW

**Comment by georgeburdell** [comment]
:warning: You are running version **2.6.2** of [barryvdh/laravel-ide-helper](https://packagist.org/packages/barryvdh/laravel-ide-helper). The latest version is **2.6.4**. You should review this dependency to see if you can run the latest version.

**Comment by georgeburdell** [comment]
:warning: You are running version **5.8.34** of [laravel/framework](https://packagist.org/packages/laravel/framework). The latest version is **6.0.0**. You should review this dependency to see if you can run the latest version.

**Comment by georgeburdell** [comment]
:warning: You are running version **1.1.5** of [maatwebsite/laravel-nova-excel](https://packagist.org/packages/maatwebsite/laravel-nova-excel). The latest version is **1.1.6**. You should review this dependency to see if you can run the latest version.

**Comment by georgeburdell** [comment]
:warning: You are running version **2.37.0** of [spatie/laravel-permission](https://packagist.org/packages/spatie/laravel-permission). The latest version is **3.0**. You should review this dependency to see if you can run the latest version.

**Comment by georgeburdell** [comment]
:warning: You are running version **2.20190710.0** of [square/connect](https://packagist.org/packages/square/connect). The latest version is **2.20190814.2**. You should review this dependency to see if you can run the latest version.

**Comment by georgeburdell** [comment]
:information_source: The following Laravel packages were updated as they are known to be compatible with version 5.8.34 of the Laravel framework. Nonetheless, you should review the _CHANGELOG_ to ensure no additional changes are needed.

- [ ] [laravel/socialite](https://github.com/laravel/socialite)

**Comment by georgeburdell** [comment]
:information_source: Shift detected your application only has the default tests. You can get a jump by adding tests by using the [Test Generator](https://laravelshift.com/laravel-test-generator) to automatically create the model factories, test classes, and sample tests cases for your Laravel application.

**Comment by JoshOldenburg** [comment]
Closed in favor of the shift to 6.0.

**Pull request closed without merging**
