### PR TITLE
Added privacy policy

### LINKED ISSUE #66: Write Privacy Policy
Given the amount of personal information that this application stores on users, it is important to inform them of how we will and will not use it.

### PR DESCRIPTION
**Pull request by kberzinch**
Adds an unprotected web route to display the privacy policy.

Closes #66.

### CODE REVIEW

**Comment by kberzinch** [comment]
It is not. We could add a footer link.

**Comment by ryanstrat** [comment]
I also support a footer link

**Comment by ryanstrat** [comment]
Regarding Content, it should be added that performing certain actions on the system will require collection of certain information.

Do we need to add anything regarding use of first/third party cookies and/or Google Analytics?

**Comment by kberzinch** [comment]
As of right now, we don't require any data besides what we get from GTED. That will change in the future, of course, and at that point we can update this document.

Your last point is covered in GT's policy and therefore I don't think it warrants inclusion here.

**Pull request merged**
